version: 2
updates:
- package-ecosystem: nuget
  labels:
    - "dependencies"
  commit-message:
    prefix: "(ci deps)"
  groups:
    microsoft:
      patterns:
      - "Microsoft.*"
      - "System.*"
  directory: "/build"
  schedule:
    interval: daily
  open-pull-requests-limit: 10

- package-ecosystem: nuget
  labels:
    - "dependencies"
  commit-message:
    prefix: "(new-cli deps)"
  groups:
    microsoft:
      patterns:
      - "Microsoft.*"
      - "System.*"    
    serilog:
      patterns:
      - "Serilog.*"
  directory: "/new-cli"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  
- package-ecosystem: nuget
  labels:
    - "dependencies"
  commit-message:
    prefix: "(deps)"
  groups:
    microsoft:
      patterns:
      - "Microsoft.*"
      - "System.*"
    analyzers:
      patterns:
      - "*Analyzers"
    serilog:
        patterns:
        - "Serilog.*"
    nunit:
      patterns:
      - "NUnit.*"
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10

- package-ecosystem: github-actions
  labels:
    - "dependencies"
  commit-message:
    prefix: "(build deps)"
  groups:
    actions:
      patterns:
      - "actions/*"    
  directory: "/"
  schedule:
    interval: daily
    
- package-ecosystem: npm
  labels:
    - "dependencies"
  commit-message:
    prefix: "(docs deps)"
  groups:
    remark:
      patterns:
      - "remark*"
  directory: "/"
  schedule:
    interval: monthly
