version: 2
updates:
  - package-ecosystem: dotnet-sdk
    milestone: 82 # Corresponds to 6.x
    labels:
      - "dependencies"
    commit-message:
      prefix: "(sdk)"
    directory: "/"
    schedule:
      interval: cron
      cronjob: "0 12 * * *"
  - package-ecosystem: nuget
    milestone: 82 # Corresponds to 6.x
    labels:
      - "dependencies"
    commit-message:
      prefix: "(deps)"
    groups:
      microsoft:
        group-by: dependency-name
        patterns:
          - "Microsoft.*"
          - "System.*"
      Microsoft_CodeAnalysis:
        group-by: dependency-name
        patterns:
          - "Microsoft.CodeAnalysis.*"
      analyzers:
        group-by: dependency-name
        patterns:
          - "*Analyzers"
      serilog:
        group-by: dependency-name
        patterns:
          - "Serilog.*"
      nunit:
        group-by: dependency-name
        patterns:
          - "NUnit.*"
      LibGit2Sharp:
        group-by: dependency-name
        patterns:
          - "LibGit2Sharp.*"
      JsonSchemaNet:
        group-by: dependency-name
        patterns:
          - "JsonSchemaNet.*"
    directories:
      - "/build"
      - "/new-cli"
      - "/src"
    schedule:
      interval: cron
      cronjob: "0 12 * * *"
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    labels:
      - "dependencies"
    commit-message:
      prefix: "(build deps)"
    groups:
      actions:
        patterns:
          - "actions/*"
    directory: "/"
    schedule:
      interval: cron
      cronjob: "0 12 * * *"

  - package-ecosystem: npm
    labels:
      - "dependencies"
    commit-message:
      prefix: "(docs deps)"
    groups:
      remark:
        patterns:
          - "remark*"
    directory: "/"
    schedule:
      interval: cron
      cronjob: "0 12 1,15 * *"
