site_name: GitVersion
theme: readthedocs
repo_url: https://github.com/GitTools/GitVersion

pages:
- Home: index.md
- Usage: 
  - Usage: usage/usage.md
  - Command Line: usage/command-line.md
  - MSBuild Task: usage/msbuild-task.md
  - NuGet Library: usage/nuget-library.md
  - Gem: usage/gem.md
- Configuration: configuration.md
- Build Server Support: 
    - Introduction: build-server-support/build-server-support.md
    - Build Servers:
      - AppVeyor: build-server-support/build-server/appveyor.md
      - Bamboo: build-server-support/build-server/bamboo.md
      - GitLab CI: build-server-support/build-server/gitlab.md
      - Continua CI: build-server-support/build-server/continua.md
      - Jenkins: build-server-support/build-server/jenkins.md
      - MyGet: build-server-support/build-server/myget.md
      - Octopus Deploy: build-server-support/build-server/octopus-deploy.md
      - TeamCity: build-server-support/build-server/teamcity.md
      - Team Build (TFS): build-server-support/build-server/teambuild.md
      - TFS Build vNext: build-server-support/build-server/tfs-build-vnext.md
- Examples: examples.md
- FAQ: faq.md
- Why?: why.md
- Who is using GitVersion: who.md

- More Info:
  - How it works: more-info/how-it-works.md
  - Dynamic Repositories: more-info/dynamic-repositories.md
  - Variables: more-info/variables.md
  - Version incrementing: more-info/version-increments.md
  - Version sources: more-info/version-sources.md
  - Incrementing per commit: more-info/incrementing-per-commit.md

- Git branching strategies:
  - Home: git-branching-strategies/index.md
  - GitFlow: git-branching-strategies/gitflow.md
  - GitHubFlow: git-branching-strategies/githubflow.md
  - GitFlow Examples: git-branching-strategies/gitflow-examples.md
  - GitHubFlow Examples: git-branching-strategies/githubflow-examples.md
  - Converting to GitFlow: git-branching-strategies/converting-to-gitflow.md
  - Creating/Updating examples: git-branching-strategies/creating-updating-examples.md

- Reference:
  - Intro to SemVer: reference/intro-to-semver.md
  - Git setup: reference/git-setup.md
  - Feature branches: reference/feature-branches.md
  - Pull requests: reference/pull-requests.md
  - Mainline development: reference/mainline-development.md
  - Continous delivery: reference/continuous-delivery.md
  - Continuous deployment: reference/continuous-deployment.md
