blank_issues_enabled: false
contact_links:
- name: Ask for help or share ideas
  url: https://github.com/GitTools/GitVersion/discussions/new/choose
  about: Ask the community for help or share ideas for new features.