name: Release
on:
  release:
    types: [published]

jobs:
  release:
    name: Trigger Build flow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.RELEASE_GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          event-type: release
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
