name: Release
on:
  release:
    types: [ published ]

jobs:
  release:
    name: Trigger ci flow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get version
        id: get-version
        shell: pwsh
        run: |
          # Finding the version from release tag
          $VERSION="${{ github.ref }}".Replace("refs/tags/", "")
          "version=$VERSION" >> $env:GITHUB_OUTPUT        
      - uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.RELEASE_GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          event-type: ci-release
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "tag": "${{ steps.get-version.outputs.version }}"}'